'''
Pentagon numbers

Problem 44
Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
'''
'''
Extremely inefficient, improvement needed
'''

def pentagon_num(i):
        return i * (3 * i - 1) / 2

def main():
    min = 100000000
    penta = []
    len = 3000
    for i in range(1,6001):
        penta.append(pentagon_num(i))
    print(penta[-1])
    for i in range(len):
        for k in range(i + 1, len):
            sum = penta[i] + penta[k]
            d = penta[k] - penta[i]
            '''print(penta[i], penta[k], sum, d)'''
            if d > min:
                print(penta[i], penta[k], sum, d)
                break
            try:
                penta.index(sum)
                penta.index(d)
                if d < min:
                    min = d
                    print(min)
                else:
                    break
            except:
                continue
    print(min)
    
if __name__ == '__main__':
    main()
