package pu1_10;

public class E02 {

	public static void main(String[] args) {
		/* 
		 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
		 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
		 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
		 */
		
		int sum = 0;
		int num1 = 1;
		int num2 = 0;
		
		while(true) {
			num1 += num2;
			if(num1 > 4000000)
				break;
			if(num1 % 2 == 0)
				sum += num1;
			num2 += num1;
			if(num2 > 4000000)
				break;
			if(num2 % 2 == 0)
				sum += num2;
		}
		System.out.println(sum);
	}

}
